language: python
python:
  - 2.7
  - 3.4
notifications:
  email: false

# Setup anaconda
before_install:
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -q
  - sudo apt-get install octave -y
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels pip beautiful-soup ipython nbformat
  - pip install -r requirements.txt
  # Coverage packages are on my binstar channel
  #- conda install --yes -c dan_blanchard python-coveralls nose-cov
  - pip install nose-cov python-coveralls
  - python setup.py install


# Recipe from http://dan-blanchard.roughdraft.io/7045057-quicker-travis-builds-that-rely-on-numpy-and-scipy-using-miniconda
# Run test
script:
  - nosetests --with-coverage --cover-package=pweave
#  - nosetests --with-cov --cov Pweave --cov-config .coveragerc --logging-level=INFO

# Calculate coverage
after_success:
   - coveralls
#  - coveralls --config_file .coveragerc
