language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
  - "sudo apt-get install octave python-scipy python-matplotlib python3-scipy python3-matplotlib"
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: nosetests