package:
  name: pweave
  version: !!str 0.25

source:
  fn: Pweave-0.25.tar.gz
  url: https://pypi.python.org/packages/f6/2f/e9735b04747ae5ef29d64e0b215fb0e11f1c89826097ac17342efebbbb84/Pweave-0.25.tar.gz#md5=d406395ee4a578c30ad498426402b8e6
  md5: d406395ee4a578c30ad498426402b8e6
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pweave = pweave:main
    #
    # Would create an entry point called pweave that calls pweave.main()

    - Pweave = pweave.scripts:weave
    - pweave = pweave.scripts:weave
    - Ptangle = pweave.scripts:tangle
    - ptangle = pweave.scripts:tangle
    - pypublish = pweave.scripts:publish
    - pweave-convert = pweave.scripts:convert


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pweave

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - Pweave --help
    - Ptangle
    - pypublish --help
    - pweave-convert --help


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    #- nose

about:
  home: http://mpastell.com/pweave
  license: BSD
  summary: 'Scientific reports with embedded python computations with reST, LaTeX or markdown'
